version: '3.1' # specify docker-compose version
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
      POSTGRES_USER: user
    volumes:
      - ./data:/var/lib/postgresql