version: '3.1' # specify docker-compose version
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
      POSTGRES_USER: user
    volumes:
      - ./data:/var/lib/postgresql
  backend:
    image: hamzaabuzahra/task
    restart: unless-stopped
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/products
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db